name: nf-core-moff-labelfree
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:

  - python=3.6
#  - moff=2.0.3
  - flashlfq=1.1.1
  - pandas=0.24.2
#  - brain-isotopic-distribution=1.5.3
  - thermorawfileparser=1.3.4
  - searchgui=4.0.33
  - peptide-shaker=2.0.25
  - unzip=6.0 
#  - mono=5.14.0.177
  - libopenblas=0.3.3
  - bioconductor-msnbase=2.16.1
  - r-msqrob=0.7.7
  

